spring.application.name=SafetyNetAlerts

# Server configuration
server.port=8080

# Logging configuration
logging.level.root=ERROR
logging.level.com.safetynet.safetynetalerts=DEBUG
# logging.level.org.springframework.boot.web.embedded.tomcat=INFO
